baseURL: https://nabizzle.github.io/

languageCode: en-us
title: "Nabeel Chowdhury"
theme: "toha"

# Manage languages
# For any more details, you can check the official documentation: https://gohugo.io/content-management/multilingual/
languages:
  en:
    languageName: English
    weight: 1

# Control TOC depth
markup:
  tableOfContents:
    startLevel: 2
    endLevel: 6
    ordered: false

  goldmark:
    renderer:
      unsafe: true

# Enable global emoji support
enableEmoji: true

# Site parameters
params:
  # Background images
  background: images/home/background2.jpg

  # The inverted logo will be used in the initial transparent navbar and
  # the main logo will be used in the non-transparent navbar.
  logo:
    main: images/home/main-logo.png
    inverted: images/home/inverted-logo.png
    favicon: images/home/favicon.svg

  # GitHub repo URL of your site
  gitRepo: https://github.com/Nabizzle/Nabizzle.github.io

  # specify whether you want to write some blog posts or not
  enableBlogPost: true

  # specify whether you want to show Table of Contents in reading page
  enableTOC: true

  # Provide newsletter configuration. This feature hasn't been implemented yet.
  # Currently, you can just hide it from the footer.
  newsletter:
    enable: false
